version: "3.9"
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.5
    command:
      - redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --node-id 0 --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "${REDPANDA_KAFKA_PORT:-9092}:9092"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info -X brokers=localhost:9092 >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
  console:
    image: docker.redpanda.com/redpandadata/console:v2.7.2
    env_file:
      - .env
    environment:
      KAFKA_BROKERS: ${KAFKA_BROKERS:-redpanda:9092}
    ports:
      - "${REDPANDA_CONSOLE_PORT:-8081}:8080"
    depends_on:
      - redpanda
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_HTTP_PORT:-8080}:8080"
    depends_on:
      - redpanda
